### ISSUE TITLE
There is no message about signing a multisig transaction when you login

### ISSUE THREAD

**Issue by Sateetje** [NemProject/NanoWallet#357] opened 2017-12-14 18:34 UTC
## Expected Behavior
Show a message about signing a multisig transaction when you login, when there is one in the queue.

## Current Behavior
No indication is shown when a multisig transaction is in the queue to be signed.

## Possible Solution
Show a popup or icon when a multisig transaction is in the queue to be signed.

## Details
W7 + Firefox Dev and Nano 2.0.2

NBXNJ2-FH2K52-ZOOI3A-2ZY4AW-YQJ7LV-AITSZX-KZWI

**Comment by QuantumMechanics** [comment] 2017-12-14 19:09
It should be like other transactions and notify you with a sound.

But most of the time multisignature transactions doesn't shows up in unconfirmed.

It is a known issue probably due to websockets

**Comment by fyahfox** [comment] 2018-05-11 16:42
could you already find a fix for this?

**Comment by fyahfox** [comment] 2018-05-11 18:16
Bounty paid. Tx hash: 82b2e1d2861de2d1cad85cfef29cc71dbfe8e06dbadc798ca73f5f32cb328903

**Closed as completed** 2019-07-31 11:16 UTC
